version: 2
updates:
  # Update pip dependencies weekly, but ignore major updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: "pip"
    open-pull-requests-limit: 10
    groups:
      python-packages:
        patterns:
          - "*"
  # Update GitHub Actions dependencies weekly, but ignore major updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      github-actions:
        patterns:
          - "*"