[project]
name = "patreon-scraper"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "selenium~=4.17.2",
    "python-dotenv~=1.0.1",
    "requests~=2.32.0",
    "aiohttp~=3.11.7",
    "pillow~=11.0.0",
    "asyncio~=3.4.3",    
]

[dependency-groups]
dev = [
    "pytest~=8.3.3",
    "pylint~=3.3.9",
]

[tool.pytest.ini_options]
pythonpath = ["src"]